### ISSUE TITLE
Help with Windows 10

### ISSUE THREAD

**Issue by itbeyond** [Culture22/cordova-windows10-zip#1]
I know you just ported this for us from another contribution but I cannot make it work. My system keeps reporting 

Exception calling native with command :: Zip :: unzip ::exception=WinRTError: The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
at ZipCSComponent.ZipImpl.<UnZipInternal>d__0.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at ZipCSComponent.ZipImpl.UnZipInternal(String sourceFileName, String destDir, ProgressDelegate progress)

Do you have any idea on why the dependency System.IO.FileSystem is not loaded or working?

**Comment by birgerstoeckelmann** [comment]
Hi @itbeyond , I got the same error in VS 2017 on Windows 10 Build 15063 in Debug/AnyCPU configuration. Switching to "Release" and concrete architecture (x64 / x86) the assembly is linkend and found at runtime. VS doesn't create native components in debug mode. Maybe this is your problem too.

So the plugin is still working for me on Windows 10.
